#!/bin/bash
#
#
# deltacloud-condor  startup script for deltacloud-condor server
#
# chkconfig: - 97 03
# description: deltacloud-condor is primary server process for the \
#    Deltacloud Core component with Condor Driver enabled.
#

[ -r /etc/sysconfig/deltacloud-condor ] && . /etc/sysconfig/deltacloud-condor

HOSTNAME=$(hostname)
HOST=${HOST:-$HOSTNAME}
ENV="${ENV:-production}"
DRIVER="${DRIVER:-condor}"
PORT="${PORT:-3005}"
LOCKFILE="${LOCKFILE:-/var/lock/subsys/deltacloud-condor }"
LOGFILE="${LOGFILE:-/var/log/deltacloud-condor/$DRIVER.log}"
export CONDOR_MAPPER_DIR="${CONDOR_MAPPER_DIR:-/var/tmp/condor-cloud}"

[ ! -d /var/log/deltacloud-condor ] && mkdir -p /var/log/deltacloud-condor
chown -R $CONDOR_USER /var/log/deltacloud-condor

exec=/usr/bin/deltacloudd-condor
prog=deltacloudd-condor
logfile="${LOGFILE:-/var/log/deltacloud-condor/$DRIVER.log}"
lockfile="${LOCKFILE:-/var/lock/subsys/deltacloud-condor}"
options="-i ${DRIVER} -e ${ENV} -p ${PORT} -r ${HOST}"

. /etc/init.d/functions

start() {
    echo -n "Starting deltacloud-condor ($HOST:$PORT): "
    daemon --user $CONDOR_USER "$exec $options >> $logfile 2>&1 &"
    RETVAL=$?
    if [ $RETVAL -eq 0 ] && touch $LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}

stop() {
    echo -n "Shutting down deltacloud-condor ($HOST:$PORT): "
    RETVAL=$?
    killproc $prog
    if [ $RETVAL -eq 0 ] && rm -f $LOCKFILE ; then
      echo_success
      echo
    else
      echo_failure
      echo
    fi
}


case "$1" in
    start)
      start
      ;;
    stop)
      stop
      ;;
    restart)
      stop
      start
      ;;
    reload)
      ;;
    force-reload)
      restart
      ;;
    status)
      status $PROG
      RETVAL=$?
      ;;
    *)
      echo "Usage: deltacloud-core {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
